FROM node:18 as dependencies
WORKDIR /usr/src/app
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

FROM node:18 as builder
WORKDIR /usr/src/app
COPY . .
COPY --from=dependencies /usr/src/app/node_modules ./node_modules
RUN yarn build

FROM node:18 as runner
WORKDIR /usr/src/app
ENV NODE_ENV production

COPY --from=builder /usr/src/app/package.json ./package.json
COPY --from=builder /usr/src/app/.keystone ./.keystone
COPY --from=builder /usr/src/app/node_modules ./node_modules

ENV DATABASE_URL $DATABASE_URL
ENV SESSION_SECRET $SESSION_SECRET
ENV FRONTEND_URL $FRONTEND_URL
ENV BACKEND_URL $BACKEND_URL
ENV PAYTURE_URL $PAYTURE_URL
ENV PAYTURE_TERMINAL_RUB $PAYTURE_TERMINAL_RUB
ENV PAYTURE_TERMINAL_USD $PAYTURE_TERMINAL_USD
ENV PAYTURE_TERMINAL_PASSWORD $PAYTURE_TERMINAL_PASSWORD
ENV NALOG_INN $NALOG_INN
ENV NALOG_PASSWORD $NALOG_PASSWORD
ENV S3_STORAGE_KEY_ID $S3_STORAGE_KEY_ID
ENV S3_STORAGE_KEY_SECRET $S3_STORAGE_KEY_SECRET
ENV MAIL_HOST $MAIL_HOST
ENV MAIL_PORT $MAIL_PORT
ENV MAIL_USER $MAIL_USER
ENV MAIL_PASS $MAIL_PASS
ENV YOOKASSA_ID $YOOKASSA_ID
ENV YOOKASSA_SECRET $YOOKASSA_SECRET

ENV PORT 3000
EXPOSE 3000
CMD ["yarn", "start"]
