version: '3.7'
services:
  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - "80:80"
  crm:
    container_name: just-study-crm
    image: { { env.IMAGE_URL } }
    restart: always
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DATABASE_URL: { { env.DATABASE_URL } }
      SESSION_SECRET: { { env.SESSION_SECRET } }
      FRONTEND_URL: { { env.FRONTEND_URL } }
      BACKEND_URL: { { env.BACKEND_URL } }
      PAYTURE_URL: { { env.PAYTURE_URL } }
      PAYTURE_TERMINAL_RUB: { { env.PAYTURE_TERMINAL_RUB } }
      PAYTURE_TERMINAL_USD: { { env.PAYTURE_TERMINAL_USD } }
      PAYTURE_TERMINAL_PASSWORD: { { env.PAYTURE_TERMINAL_PASSWORD } }
      NALOG_INN: { { env.NALOG_INN } }
      NALOG_PASSWORD: { { env.NALOG_PASSWORD } }
      S3_STORAGE_KEY_ID: { { env.SERVICE_KEY_ID } }
      S3_STORAGE_KEY_SECRET: { { env.SERVICE_KEY_SECRET } }
      YOOKASSA_ID: { { env.YOOKASSA_ID } }
      YOOKASSA_SECRET: { { env.YOOKASSA_SECRET } }
      AWS_ACCESS_KEY_ID: { { env.SERVICE_KEY_ID } }
      AWS_SECRET_ACCESS_KEY: { { env.SERVICE_KEY_SECRET } }
