version: '3.7'

services:
  nginx:
    container_name: nginx
    image: {{ env.NGINX_IMAGE }}
    ports:
      - '80:80'
      - '443:443'
    restart: always
    environment:
      NGINX_CERT: {{ env.NGINX_CERT }}
      NGINX_CERT_KEY: {{ env.NGINX_CERT_KEY }}
    depends_on:
      - backend
      - site
      - fluentbit
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: nginx.logs

  site:
    container_name: site
    image: {{ env.SITE_IMAGE }}
    restart: always
    depends_on:
     - fluentbit
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224

  backend:
    container_name: backend
    image: {{ env.BACKEND_IMAGE }}
    restart: always
    environment:
      NODE_ENV: {{ env.NODE_ENV }}
      DATABASE_URL: {{ env.DATABASE_URL }}
      SESSION_SECRET: {{ env.SESSION_SECRET }}
      FRONTEND_URL: {{ env.FRONTEND_URL }}
      BACKEND_URL: {{ env.BACKEND_URL }}
      PAYTURE_URL: {{ env.PAYTURE_URL }}
      PAYTURE_TERMINAL_RUB: {{ env.PAYTURE_TERMINAL_RUB }}
      PAYTURE_TERMINAL_USD: {{ env.PAYTURE_TERMINAL_USD }}
      PAYTURE_TERMINAL_PASSWORD: {{ env.PAYTURE_TERMINAL_PASSWORD }}
      NALOG_INN: {{ env.NALOG_INN }}
      NALOG_PASSWORD: {{ env.NALOG_PASSWORD }}
      S3_STORAGE_KEY_ID: {{ env.SERVICE_KEY_ID }}
      S3_STORAGE_KEY_SECRET: {{ env.SERVICE_KEY_SECRET }}
      YOOKASSA_ID: {{ env.YOOKASSA_ID }}
      YOOKASSA_SECRET: {{ env.YOOKASSA_SECRET }}
      AWS_ACCESS_KEY_ID: {{ env.SERVICE_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: {{ env.SERVICE_KEY_SECRET }}
      SKIP_NALOG: {{ env.SKIP_NALOG }}
      TEST_EMAIL: {{ env.TEST_EMAIL }}
    depends_on:
      - fluentbit
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224

  fluentbit:
    container_name: fluentbit
    image: cr.yandex/yc/fluent-bit-plugin-yandex:v2.0.3-fluent-bit-1.9.3
    ports:
      - 24224:24224
      - 24224:24224/udp
    restart: always
    environment:
      YC_GROUP_ID: {{ env.YC_GROUP_ID }}
    volumes:
      - /etc/fluentbit/fluentbit.conf:/fluent-bit/etc/fluent-bit.conf
      - /etc/fluentbit/parsers.conf:/fluent-bit/etc/parsers.conf
