version: '3.7'

services:
  caddy:
    container_name: caddy
    image: {{ env.CADDY_IMAGE }}
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - internet

  site:
    container_name: site
    image: {{ env.SITE_IMAGE }}
    restart: always
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
    networks:
      - internet

  backend:
    container_name: backend
    image: {{ env.BACKEND_IMAGE }}
    restart: always
    environment:
      NODE_ENV: {{ env.NODE_ENV }}
      DATABASE_URL: {{ env.DATABASE_URL }}
      SESSION_SECRET: {{ env.SESSION_SECRET }}
      FRONTEND_URL: {{ env.FRONTEND_URL }}
      BACKEND_URL: {{ env.BACKEND_URL }}
      PAYTURE_URL: {{ env.PAYTURE_URL }}
      PAYTURE_TERMINAL_RUB: {{ env.PAYTURE_TERMINAL_RUB }}
      PAYTURE_TERMINAL_USD: {{ env.PAYTURE_TERMINAL_USD }}
      PAYTURE_TERMINAL_PASSWORD: {{ env.PAYTURE_TERMINAL_PASSWORD }}
      NALOG_INN: {{ env.NALOG_INN }}
      NALOG_PASSWORD: {{ env.NALOG_PASSWORD }}
      SERVICE_KEY_ID: {{ env.SERVICE_KEY_ID }}
      SERVICE_KEY_SECRET: {{ env.SERVICE_KEY_SECRET }}
      YOOKASSA_ID: {{ env.YOOKASSA_ID }}
      YOOKASSA_SECRET: {{ env.YOOKASSA_SECRET }}
      AWS_ACCESS_KEY_ID: {{ env.SERVICE_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: {{ env.SERVICE_KEY_SECRET }}
      SKIP_NALOG: {{ env.SKIP_NALOG }}
      TEST_EMAIL: {{ env.TEST_EMAIL }}
    depends_on:
      - mysql
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
    networks:
      - no-internet
      - internet

  fluentbit:
    container_name: fluentbit
    image: cr.yandex/yc/fluent-bit-plugin-yandex:v2.0.3-fluent-bit-1.9.3
    ports:
      - 24224:24224
      - 24224:24224/udp
    restart: always
    environment:
      YC_GROUP_ID: {{ env.YC_GROUP_ID }}
    volumes:
      - /etc/fluentbit/fluentbit.conf:/fluent-bit/etc/fluent-bit.conf
      - /etc/fluentbit/parsers.conf:/fluent-bit/etc/parsers.conf
    networks:
      - internet

  mysql:
    container_name: mysql
    image: mysql:8.2.0
    restart: always
    expose:
      - 3306
    volumes:
      - /etc/mysql:/var/lib/mysql
    networks:
      - no-internet

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql
    networks:
      - no-internet
      - internet

networks:
  no-internet:
    driver: bridge
    internal: true
  internet:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
