#cloud-config
write_files:
  - content: |
      [SERVICE]
          Flush         1
          Log_File      /var/log/fluentbit.log
          Log_Level     error
          Daemon        off
          Parsers_File  /fluent-bit/etc/parsers.conf
      
      [INPUT]
          Name              forward
          Listen            0.0.0.0
          Port              24224
          Buffer_Chunk_Size 1M
          Buffer_Max_Size   6M
      
      [FILTER]
          Name record_modifier
          Match *
          Whitelist_key log
      
      
      [FILTER]
          Name rewrite_tag
          Match nginx.logs
          Rule $log access_log nginx.access false
      
      [FILTER]
          Name parser
          Match nginx.access
          Key_Name log
          Parser nginx_parser
      
      [OUTPUT]
          Name            yc-logging
          Match           *
          group_id        ${YC_GROUP_ID}
          message_key     text
          level_key       severity
          default_level   WARN
          authorization   instance-service-account
    path: /etc/fluent-bit/fluentbit.conf
  - content: |
      [PARSER]
          Name   nginx_parser
          Format regex
          Regex  ^access_log (?<remote_address>[^ ]*) "(?<method>\S+)(?: +(?<path>[^\"]*?)(?: +\S*)?)?" (?<status>[^ ]*) "(?<http_user_agent>[^\"]*)"$
          Types  status:integer
    path: /etc/fluent-bit/parsers.conf

users:
  - name: juststudy
    groups: sudo
    shell: /bin/bash
    sudo: [ 'ALL=(ALL) NOPASSWD:ALL' ]
    ssh_authorized_keys:
      - {{ env.SSH_KEY }}
