#cloud-config
write_files:
  - content: |
      [SERVICE]
          Flush         1
          Log_File      /var/log/fluentbit.log
          Log_Level     error
          Daemon        off

      [INPUT]
          Name              forward
          Listen            0.0.0.0
          Port              24224
          Buffer_Chunk_Size 1M
          Buffer_Max_Size   6M
      
      [FILTER]
          Name record_modifier
          Match *
          Whitelist_key log
          Reserve_Data On
      
      [FILTER]
          Name rewrite_tag
          Match nginx.logs
          Rule $log access_log nginx.access false
          Reserve_Data On
      
      [FILTER]
          Name parser
          Match nginx.access
          Key_Name log
          Parser nginx_parser
          Reserve_Data On
      
      [OUTPUT]
          Name            yc-logging
          Match           *
          group_id        ${YC_GROUP_ID}
          message_key     log
          level_key       severity
          default_level   INFO
          authorization   instance-service-account
    path: /etc/fluentbit/fluentbit.conf

users:
  - name: juststudy
    groups: sudo
    shell: /bin/bash
    sudo: [ 'ALL=(ALL) NOPASSWD:ALL' ]
    ssh_authorized_keys:
      - {{ env.SSH_KEY }}
