name: Deploy

on:
  push:
    branches: [ "master" ]

jobs:
  deploy-docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to Yandex Cloud Container Registry
        id: login-cr
        uses: yc-actions/yc-cr-login@v1
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}

      - name: Build, tag, and push image to Yandex Cloud Container Registry
        env:
          CR_REGISTRY: crpt6ftcvvm3ts7j581s
          CR_REPOSITORY: crm-back
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG .
          docker push cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG
  update-server:
    needs:
      - deploy-docker
    runs-on: ubuntu-latest
    environment:
      name: prod
      url: https://juststudy.online
    steps:
      - uses: actions/checkout@v3
      - name: Deploy Serverless Container
        id: deploy-sls-container
        uses: yc-actions/yc-sls-container-deploy@v2
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
          container-name: just-study-crm
          folder-id: b1g4s4k8tj83buc1hdoq
          revision-service-account-id: ajesfn13n9hlksu185rq
          revision-cores: 1
          revision-memory: 512Mb
          revision-core-fraction: 100
          revision-concurrency: 8
          revision-image-url: cr.yandex/crpt6ftcvvm3ts7j581s/crm-back:${{ github.sha }}
          revision-execution-timeout: 100
          revision-provisioned: 0
          revision-env: |
            NODE_ENV=production
            DATABASE_URL=${{ secrets.DATABASE_URL }}
            SESSION_SECRET=${{ secrets.SESSION_SECRET }}
            FRONTEND_URL=${{ secrets.FRONTEND_URL }}
            BACKEND_URL=${{ secrets.BACKEND_URL }}
            PAYTURE_URL=${{ secrets.PAYTURE_URL }}
            PAYTURE_TERMINAL_RUB=${{ secrets.PAYTURE_TERMINAL_RUB }}
            PAYTURE_TERMINAL_USD=${{ secrets.PAYTURE_TERMINAL_USD }}
            PAYTURE_TERMINAL_PASSWORD=${{ secrets.PAYTURE_TERMINAL_PASSWORD }}
            NALOG_INN=${{ secrets.NALOG_INN }}
            NALOG_PASSWORD=${{ secrets.NALOG_PASSWORD }}
            S3_STORAGE_KEY_ID=${{ secrets.S3_STORAGE_KEY_ID }}
            S3_STORAGE_KEY_SECRET=${{ secrets.S3_STORAGE_KEY_SECRET }}
            MAIL_HOST=${{ secrets.MAIL_HOST }}
            MAIL_PORT=${{ secrets.MAIL_PORT }}
            MAIL_USER=${{ secrets.MAIL_USER }}
            MAIL_PASS=${{ secrets.MAIL_PASS }}
            YOOKASSA_ID=${{ secrets.YOOKASSA_ID }}
            YOOKASSA_SECRET=${{ secrets.YOOKASSA_SECRET }}
