name: Deploy-dev

on:
  push:
    branches: [ "develop" ]

env:
  CR_REGISTRY: crpt6ftcvvm3ts7j581s
  BACKEND_IMAGE: cr.yandex/crpt6ftcvvm3ts7j581s/crm-back:${{ github.sha }}
  SITE_IMAGE: cr.yandex/crpt6ftcvvm3ts7j581s/site:${{ github.sha }}
  NGINX_IMAGE: cr.yandex/crpt6ftcvvm3ts7j581s/nginx:${{ github.sha }}
  DOCKER_BUILDKIT: 1

jobs:
  build-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: crm
    environment:
      name: dev

    steps:
      - uses: actions/checkout@v3

      - name: Login to Yandex Cloud Container Registry
        id: login-cr
        uses: yc-actions/yc-cr-login@v1
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}

      - name: Build, tag, and push image to Yandex Cloud Container Registry
        env:
          CR_REPOSITORY: crm-back
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG .
          docker push cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG

  build-site:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: site
    environment:
      name: dev

    steps:
      - uses: actions/checkout@v3

      - name: Create env file
        run: |
          touch .env
          echo FRONTEND_URL=${{vars.FRONTEND_URL}} >> .env
          echo NEXT_PUBLIC_FRONTEND_URL=${{vars.FRONTEND_URL}} >> .env
          cat .env

      - name: Login to Yandex Cloud Container Registry
        id: login-cr
        uses: yc-actions/yc-cr-login@v1
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}

      - name: Build, tag, and push image to Yandex Cloud Container Registry
        env:
          CR_REPOSITORY: site
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG .
          docker push cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG

  build-nginx:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: nginx
    environment:
      name: dev

    steps:
      - uses: actions/checkout@v3

      - name: Login to Yandex Cloud Container Registry
        id: login-cr
        uses: yc-actions/yc-cr-login@v1
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}

      - name: Build, tag, and push image to Yandex Cloud Container Registry
        env:
          CR_REPOSITORY: nginx
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG .
          docker push cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG

  update-coi:
    needs: [ build-backend, build-site, build-nginx ]
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy COI VM
        id: deploy-coi
        uses: yc-actions/yc-coi-deploy@v1.2.0
        env:
          BACKEND_IMAGE: ${{ vars.BACKEND_IMAGE }}
          SITE_IMAGE: ${{ vars.SITE_IMAGE }}
          NGINX_IMAGE: ${{ vars.NGINX_IMAGE }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          NODE_ENV: production
          SKIP_NALOG: true
          TEST_EMAIL: true
          DATABASE_URL: ${{ vars.DATABASE_URL }}
          FRONTEND_URL: ${{ vars.FRONTEND_URL }}
          SERVICE_KEY_ID: ${{ vars.SERVICE_KEY_ID }}
          SERVICE_KEY_SECRET: ${{ vars.SERVICE_KEY_SECRET }}
          NGINX_CERT: ${{ secrets.NGINX_CERT }}
          NGINX_CERT_KEY: ${{ secrets.NGINX_CERT_KEY }}
          YC_GROUP_ID: ${{ vars.YC_GROUP_ID }}
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
          folder-id: b1g4s4k8tj83buc1hdoq
          vm-name: just-study-dev
          vm-service-account-id: aje38cdteqcfo55pe02h
          vm-cores: 2
          vm-memory: 1GB
          vm-disk-size: 30Gb
          vm-core-fraction: 20
          vm-zone-id: ru-central1-a
          vm-subnet-id: e9b0mid7cobe4c9paohd
          docker-compose-path: './yandex-cloud/docker-compose.yaml'
          user-data-path: './yandex-cloud/user-data.yaml'
