name: Deploy

on:
  push:
    branches: [ "master" ]

jobs:
  deploy-docker:
    runs-on: ubuntu-latest
    environment:
      name: prod
      url: https://juststudy.online

    steps:
      - uses: actions/checkout@v3

      - name: Create env file
        run: |
          touch .env
          echo DATABASE_URL=${{ secrets.DATABASE_URL }} >> .env
          echo SESSION_SECRET=${{ secrets.SESSION_SECRET }} >> .env
          echo FRONTEND_URL=${{ secrets.FRONTEND_URL }} >> .env
          echo BACKEND_URL=${{ secrets.BACKEND_URL }} >> .env
          echo PAYTURE_URL=${{ secrets.PAYTURE_URL }} >> .env
          echo PAYTURE_TERMINAL_RUB=${{ secrets.PAYTURE_TERMINAL_RUB }} >> .env
          echo PAYTURE_TERMINAL_USD=${{ secrets.PAYTURE_TERMINAL_USD }} >> .env
          echo PAYTURE_TERMINAL_PASSWORD=${{ secrets.PAYTURE_TERMINAL_PASSWORD }} >> .env
          echo NALOG_INN=${{ secrets.NALOG_INN }} >> .env
          echo NALOG_PASSWORD=${{ secrets.NALOG_PASSWORD }} >> .env
          echo S3_STORAGE_KEY_ID=${{ secrets.S3_STORAGE_KEY_ID }} >> .env
          echo S3_STORAGE_KEY_SECRET=${{ secrets.S3_STORAGE_KEY_SECRET }} >> .env
          echo MAIL_HOST=${{ secrets.MAIL_HOST }} >> .env
          echo MAIL_PORT=${{ secrets.MAIL_PORT }} >> .env
          echo MAIL_USER=${{ secrets.MAIL_USER }} >> .env
          echo MAIL_PASS=${{ secrets.MAIL_PASS }} >> .env
          echo YOOKASSA_ID=${{ secrets.YOOKASSA_ID }} >> .env
          echo YOOKASSA_SECRET=${{ secrets.YOOKASSA_SECRET }} >> .env
          cat .env

      - name: Login to Yandex Cloud Container Registry
        id: login-cr
        uses: yc-actions/yc-cr-login@v1
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}

      - name: Build, tag, and push image to Yandex Cloud Container Registry
        env:
          CR_REGISTRY: crpt6ftcvvm3ts7j581s
          CR_REPOSITORY: crm-back
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG .
          docker push cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG
  update-server:
    needs:
      - deploy-docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy Serverless Container
        id: deploy-sls-container
        uses: yc-actions/yc-sls-container-deploy@v2
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
          container-name: just-study-crm
          folder-id: b1g4s4k8tj83buc1hdoq
          revision-service-account-id: ajesfn13n9hlksu185rq
          revision-cores: 1
          revision-memory: 512Mb
          revision-core-fraction: 100
          revision-concurrency: 8
          revision-image-url: cr.yandex/crpt6ftcvvm3ts7j581s/crm-back:${{ github.sha }}
          revision-execution-timeout: 10
